# Generated by Django 5.1.3 on 2024-11-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_emi_custom_payment_dates_alter_emi_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='emi',
            name='custom_frequency_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emi',
            name='frequency',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Custom Frequency', 'Custom Frequency'), ('Custom Dates', 'Custom Dates')], max_length=20),
        ),
    ]
