# Generated by Django 5.1.3 on 2024-12-05 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_emi_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='amount_limit',
            new_name='limit',
        ),
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.category'),
        ),
    ]
